config/routes.rb
Rails.application.routes.draw do
  
  get 'contacts/new'

  scope :module => 'buttercms' do
    get '/categories/:slug' => 'categories#show', :as => :buttercms_category
    get '/author/:slug' => 'authors#show', :as => :buttercms_author

    get '/blog/rss' => 'feeds#rss', :format => 'rss', :as => :buttercms_blog_rss
    get '/blog/atom' => 'feeds#atom', :format => 'atom', :as => :buttercms_blog_atom
    get '/blog/sitemap.xml' => 'feeds#sitemap', :format => 'xml', :as => :buttercms_blog_sitemap

    get '/blog(/page/:page)' => 'posts#index', :defaults => {:page => 1}, :as => :buttercms_blog
    get '/blog/:slug' => 'posts#show', :as => :buttercms_post
  end

  resources :charges
  
  get 'static_pages/home'
  
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  
  get '/why', to: 'static_pages#why'

  get '/donate', to: 'static_pages#donate'
  
  resources :contacts, only: [:new, :create]
  
  get '/contacts/thanks', to: 'contacts#thanks'

  get '/programs', to: 'static_pages#programs'
  
  get '/privacy', to: 'static_pages#privacy'
  
  get '/schools', to: 'static_pages#schools'
  
  get '/resources', to: 'static_pages#resources'
  
  get '/thanks', to: 'static_pages#thanks'
  
  get '/recruitment', to: 'static_pages#recruitment'
  
  get '/blog', to: 'buttercms#blog'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Website Contact Form",
      :to => "hkawashima@suppliesfordreams.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/buttercms/authors_controller.rb
class Buttercms::AuthorsController < Buttercms::BaseController
  def show
    @author = ButterCMS::Author.find(params[:slug], :include => :recent_posts)
  end
end

app/controllers/buttercms/base_controller.rb
class Buttercms::BaseController < ActionController::Base
  # You can of course change this layout to your main application layout
  # to have your blog match the rest of your site.
  layout 'buttercms/default'
end

app/controllers/buttercms/categories_controller.rb
class Buttercms::CategoriesController < Buttercms::BaseController
  def show
    @category = ButterCMS::Category.find(params[:slug], :include => :recent_posts)
  end
end

app/controllers/buttercms/feeds_controller.rb
class Buttercms::FeedsController < Buttercms::BaseController
  def sitemap
    feed = ButterCMS::Feed.find(:sitemap)

    render :xml => feed.data
  end

  def atom
    feed = ButterCMS::Feed.find(:atom)

    render :xml => feed.data
  end

  def rss
    feed = ButterCMS::Feed.find(:rss)

    render :xml => feed.data
  end
end

app/controllers/buttercms/posts_controller.rb
class Buttercms::PostsController < Buttercms::BaseController
  def index
    @posts = ButterCMS::Post.all(:page => params[:page], :page_size => 10)

    @next_page = @posts.meta.next_page
    @previous_page = @posts.meta.previous_page
  end

  def show
    @post = ButterCMS::Post.find(params[:slug])

    @next_post = @post.meta.next_post
    @previous_post = @post.meta.previous_post
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
end

def create
  @amount = params[:amount]

  @amount = @amount.gsub('$', '').gsub(',', '')

  begin
    @amount = Float(@amount).round(2)
  rescue
    flash[:error] = 'Charge not completed. Please enter a valid amount in USD ($).'
    redirect_to new_charge_path
    return
  end

  @amount = (@amount * 100).to_i # Must be an integer!

  if @amount < 500
    flash[:error] = 'Charge not completed. Donation amount must be at least $5.'
    redirect_to new_charge_path
    return
  end

  Stripe::Charge.create(
    :amount => @amount,
    :currency => 'usd',
    :source => params[:stripeToken],
    :receipt_email => params[:stripeEmail],
    :description => 'Donation'
  )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new 
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
  redirect_to contacts_thanks_path, notice: 'Message sent successfully'
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = ButterCMS::Post.all
  end

  def about
  end

  def donate
  end

  def contact
  end

  def programs
    @posts = ButterCMS::Post.all
  end
  
  def schools
  end
  
  def privacy
  end
  
  def resources
  end
  
  def thanks
  end
  
  def recruitment
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/buttercms/authors/show.html.erb
<%= content_for :html_title, "#{@author.first_name} #{@author.last_name}" %>
<%= content_for :meta_description, @author.bio %>

<!-- Author name -->
<h2><%= @author.first_name %> <%= @author.last_name %></h2>

<!-- Author profile -->
<% if @author.profile_image %>
  <img src="<%= @author.profile_image %>" />
<% end %>

<p>Title: <%= @author.title %></p>
<p>Bio: <%= @author.bio %></p>

<!-- Recent posts -->
<h4>Recent posts</h4>

<ul>
  <% @author.recent_posts.each do |post| %>
    <li><%= render :partial => 'buttercms/posts/post', :locals => {:post => post} %></li>
  <% end %>
</ul>

app/views/buttercms/categories/show.html.erb
<%= content_for :html_title, @category.name %>

<!-- Category name -->
<h2><%= @category.name %></h2>

<!-- Recent posts -->
<h4>Recent posts</h4>

<ul>
  <% @category.recent_posts.each do |post| %>
    <li><%= render :partial => 'buttercms/posts/post', :locals => {:post => post} %></li>
  <% end %>
</ul>

app/views/buttercms/posts/_post.html.erb
<div class="card">
  <!-- Featured image -->
  <%= image_tag(post.featured_image, style: "width: 100%;") if post.featured_image %>
  <div class="card-body">
    <h5 class="card-title"><%= link_to post.title, buttercms_post_path(post.slug), :title => post.title %></h5>
    <p class="card-text">by <%= link_to "#{post.author.first_name} #{post.author.last_name}", buttercms_author_path(post.author.slug) %></p>
    <p><%= post.summary %></p>
  </div>
</div>

app/views/buttercms/posts/index.html.erb
<% provide(:title, "Blog") %>
<section id="blog-title" class="bg-dark-blue">
  <div class="container py-6">
    <div class="row">
      <div class="col-md-12 col-12 text-center">
        <h1 class="text-white">Blog</h1>
      </div>
    </div>
  </div>
</section>
<section id="blog-content">
  <div class="container py-6">
    <div class="row">
      <div class="col-md-12 col-12">
        <div class="card-deck">
          <!-- List of posts -->
          <% @posts.each do |post| %>
            <%= render :partial => 'post', :locals => {:post => post} %>
          <% end %>
        </div>
        <!-- Pagination links -->
        <div>
          <% if @previous_page %>
            <%= link_to "Prev", buttercms_blog_path(:page => @previous_page) %>
          <% end %>
        
          <% if @next_page %>
            <%= link_to "Next", buttercms_blog_path(:page => @next_page) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/buttercms/posts/show.html.erb
<%= content_for :html_title, @post.seo_title %>
<%= content_for :meta_description, @post.meta_description %>
<% provide(:title, "Blog") %>
<section id="blog-title">
  <div class="container pt-6 pb-3">
    <div class="row">
      <div class="offset-md-2 col-md-8 col-12">
        <!-- Post title -->
        <h1 class="pb-2"><%= @post.title %></h1>
        <!-- Post date and author -->
        <p>Posted on <%= Time.parse(@post.published).strftime('%B %d, %Y') %> by <%= link_to "#{@post.author.first_name} #{@post.author.last_name}", buttercms_author_path(@post.author.slug) %></p>
      </div>
    </div>
  </div>
</section>
<section id="blog-content">
  <div class="container pb-6">
    <div class="row">
      <div class="offset-md-2 col-md-8 col-12">
        <!-- Post body -->
        <%= @post.body.html_safe %>
      </div>
    </div>
  </div>
</section>

app/views/charges/create.html.erb
<% provide(:title, "Thank you") %>
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>
<h2>Thank you!</h2>
<p>Your donation of <strong><%= number_to_currency(@amount * 0.01) %></strong>
 has been received.</p>

app/views/charges/new.html.erb
<h1>Charges#new</h1>
<p>Find me in app/views/charges/new.html.erb</p>
<%= form_tag charges_path, :class => 'donation-form' do %>
  <div id="error_explanation">
    <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
    <% end %>
  </div>
  <article>
    <%= text_field_tag :amount, "", :value => '50' %>
    <span class="preinput" data-reactid="4">$</span>
  </article>
  <article>
    <%= hidden_field_tag(:stripeToken) %>
  </article>
  <article>
    <%= hidden_field_tag(:stripeEmail) %>
  </article>
  <button id='donateButton' class="btn-primary btn-donate">Donate</button>
  <div class="donate-check"><a href="http://www.suppliesfordreams.org/about-us/contact/" target="_blank">Give by Check or Cash</a></div>
<% end %>

<script>
  var handler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    locale: 'auto',
    name: 'Supplies for Dreams',
    image: 'https://s3.amazonaws.com/stripe-uploads/acct_15DO9aI7lB90VBFAmerchant-icon-1419463408487-logo-1.png',
    description: 'Donation',
    billingAddress: 'true',
    token: function(token) {
      $('input#stripeToken').val(token.id);
      $("input#stripeEmail").val(token.email);
      $('form').submit();
    }
  });
  
  $('#donateButton').on('click', function(e) {
    e.preventDefault();
  
    $('#error_explanation').html('');
  
    var amount = $('input#amount').val();
    amount = amount.replace(/\$/g, '').replace(/\,/g, '')
  
    amount = parseFloat(amount);
  
    if (isNaN(amount)) {
      $('#error_explanation').html('<p>Please enter a valid amount in USD ($).</p>');
    }
    else if (amount < 5.00) {
      $('#error_explanation').html('<p>Donation amount must be at least $5.</p>');
    }
    else {
      amount = amount * 100; // Needs to be an integer!
      handler.open({
        amount: Math.round(amount)
      })
    }
  });
  $(window).on('popstate', function() {
    handler.close();
  });
</script>

app/views/layouts/_blog.html.erb
<h2>Posts</h2>

<!-- List of posts -->
<% @posts.each do |post| %>
  <%= render :partial => 'post', :locals => {:post => post} %>
<% end %>

<!-- Pagination links -->
<div>
  <% if @previous_page %>
    <%= link_to "Prev", buttercms_blog_path(:page => @previous_page) %>
  <% end %>

  <% if @next_page %>
    <%= link_to "Next", buttercms_blog_path(:page => @next_page) %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark-blue">
  <div class="container">
    <div class="row footer-top text-muted pt-6 pb-3">
      <div class="col-md-6 col-12 mobile-pb-4">
        <%= link_to(raw("<i class='fab fa-facebook-f'></i>"), 'https://www.facebook.com/supplies4dreams/') %>
        <%= link_to(raw("<i class='fab fa-instagram'></i>"), 'https://www.instagram.com/supplies4dreams/') %>
        <%= link_to(raw("<i class='fab fa-twitter'></i>"), 'https://twitter.com/supplies4dreams') %>
        <p style="color: #919eab !important;">P.O. Box 8130 <br />Evanston, IL 60204</p>
      </div>
      <div class="col-md-2 col-12 mobile-pb-4">
        <p class="font-weight-bold">GET TO KNOW US</p>
        <p><%= link_to 'Our programs', programs_path %></p>
        <p><%= link_to 'About us', about_path %></p>
        <p><%= link_to 'Blog', blog_path %></p>
      </div>
      <div class="col-md-2 col-12 mobile-pb-4">
        <p class="font-weight-bold">RESOURCES</p>
        <p><%= link_to 'Annual reports', resources_path %></p>
        <p><%= link_to 'Financials', resources_path %></p>
      </div>
      <div class="col-md-2 col-12 mobile-pb-4">
        <p class="font-weight-bold">GET INVOLVED</p>
        <p><%= link_to 'Recruitment', recruitment_path %></p>
        <p><%= link_to 'Volunteer', contacts_new_path %></p>
        <p><%= link_to 'Contact us', contacts_new_path %></p>
      </div>
    </div>
    <div class="row footer-bottom py-3">
      <div class="col-12 text-center">
        <p><%= link_to 'Privacy Policy', privacy_path %></p>
        <p class="text-muted">&copy; Copyright 2019 Supplies for Dreams, Inc. is a 501(c)3 | EIN: 32-0270714</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% if current_page?(resources_path) %>
  <nav class="navbar navbar-expand-md fixed-top navbar-transparent navbar-light">
  <% elsif current_page?(programs_path) || current_page?(why_path) || current_page?(recruitment_path) %>
  <nav class="navbar navbar-expand-md fixed-top navbar-transparent navbar-dark">
  <% else %>
  <nav class="navbar navbar-expand-md fixed-top navbar-white navbar-light">
  <% end %>
    <div class="container d-flex justify-content-between">
      <% if current_page?(programs_path) || current_page?(why_path) || current_page?(recruitment_path) %>
      <%= link_to image_tag("sfd_logo_white.png", alt: "Supplies for Dreams logo", class: "nav-logo"), '/' %>
      <% else %>
      <%= link_to image_tag("sfd_logo.png", alt: "Supplies for Dreams logo", class: "nav-logo"), '/' %>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Why CPS", why_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Our Programs", programs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About Us", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Recruitment", recruitment_path, class: "nav-link" %>
          </li>
        </ul>
        <a href="/donate"><button class="btn btn-red my-2 my-sm-0" type="submit">DONATE</button></a>
      </div>
    </div>
  </nav>
</header>

app/views/static_pages/_post.html.erb
<div class="card shadow">
  <%= image_tag(post.featured_image, :class => "img_preview") if post.featured_image %>
  <div class="card-body">
    <h5 class="card-title font-weight-bold"><%= link_to post.title, buttercms_post_path(post.slug), :title => post.title %></h5>
  </div>
  <div class="card-footer">
    <%= link_to(raw("Read story <i class='fas fa-arrow-right'></i>"), buttercms_post_path(post.slug)) %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
<section id="about-title">
  <div class="py-6">
    <div class="container">
      <div class="row text-center">
        <div class="offset-md-1 col-md-10 col-12">
          <h1>Our Mission is to Equalize Learning Opportunities</h1>
          <p class="p-large pt-4">We see a world where the opportunity to learn and achieve is not determined by a person’s neighborhood or class, but by that individual’s passion and persistence for learning. Supplies for Dreams partners with local universities to provide Chicago Public Schools students with basic resources and extracurricular opportunities.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="about-principles" class="bg-grey">
  <div class="container py-6">
    <div class="row">
      <div class="col-md-6 col-12 mobile-pb-4">
        <h1 class="pb-4">Our Principles</h1>
        <h5 class="font-weight-bold">Focus on core competencies</h5>
          <p class="pb-4">We invest in our strengths and partner with other organizations where we lack expertise. Increase funding for programs focused on providing rich extra-curricular experiences.</p>
          <h5 class="font-weight-bold">Increase investment in technology</h5>
          <p class="pb-4">We actively explore technologies that can help students better engage with educational content and enhance extra-curricular experiences.</p>
          <h5 class="font-weight-bold">Leverage Chicago universities and colleges</h5>
          <p>We believe in the power of university and college students to make a difference in their communities. We currently operate at Northwestern University, Loyola University, and University of Chicago with plans to expand further.</p>
      </div>
      <div class="col-md-6 col-12 align-self-center">
        <div class="spotlight-circles">
        <div class="spotlight-circles-interior">
          <div class="spotlight-circles-content">
            <p class="spotlight-circles-content__heading">SFD’s next big plan, to be implemented in <strong>2023,</strong> is neighborhood Field Trips.</p>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</section>
<section id="about-partners">
  <div class="container py-6">
    <div class="row">
      <div class="offset-md-2 col-md-8 col-12 text-center">
        <h1>Our Partners</h1>
        <p class="p-large py-4">Our work would not be possible without the generous support of our partner organizations.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 col-6 align-self-center mobile-pb">
        <%= link_to image_tag("nu_logo.png", alt: "NU logo") %>
      </div>
      <div class="col-md-2 col-6 align-self-center mobile-pb">
        <%= link_to image_tag("loyola_logo.png", alt: "Loyola logo") %>
      </div>
      <div class="col-md-2 col-6 align-self-center mobile-pb">
        <%= link_to image_tag("uc_logo.png", alt: "UC logo") %>
      </div>
      <div class="col-md-2 col-6 align-self-center mobile-pb">
        <%= link_to image_tag("f4d_logo.png", alt: "F4D logo") %>
      </div>
      <div class="col-md-2 col-6 align-self-center mobile-pb">
        <%= link_to image_tag("cis_logo.png", alt: "CIS logo") %>
      </div>
      <div class="col-md-2 col-6 align-self-center mobile-pb">
        <%= link_to image_tag("cc_logo.png", alt: "CC logo") %>
      </div>
    </div>
  </div>
</section>
<section id="about-card">
  <div class="container py-6 mobile-py-6">
    <div class="row">
      <div class="col-12 col-md-12">
        <div class="card-deck">
          <div class="card shadow">
            <div class="card-body">
              <i class="fas fa-large fa-hands"></i>
              <h5 class="card-title font-weight-bold">Volunteering opportunities</h5>
              <p>We're always on the look for new and eager volunteers. Come on a field trip with our students.</p>
            </div>
            <div class="card-footer">
              <%= link_to(raw("Learn more <i class='fas fa-arrow-right'></i>"), contacts_new_path) %>
            </div>
          </div>
          <div class="card shadow">
            <div class="card-body">
              <i class="far fa-large fa-paper-plane"></i>
              <h5 class="card-title font-weight-bold">Contact us</h5>
              <p>Got a question about Supplies for Dreams? Send us an email and we will respond within 48 hours.</p>
            </div>
            <div class="card-footer">
              <%= link_to(raw("Email us <i class='fas fa-arrow-right'></i>"), contacts_new_path) %>
            </div>
          </div>
          <div class="card shadow">
            <div class="card-body">
              <i class="far fa-large fa-file-alt"></i>
              <h5 class="card-title font-weight-bold">Annual reports</h5>
              <p>We are committed to accountability and transparency. Read our annual reports and view our financials.</p>
            </div>
            <div class="card-footer">
              <%= link_to(raw("Read more <i class='fas fa-arrow-right'></i>"), resources_path) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/donate.html.erb
<% provide(:title, "Donate") %>
<section id="donate-banner">
  <div class="container py-6">
    <div class="row">
      <div class="offset-md-7 col-md-5 col-12">
        <script src="https://donorbox.org/widget.js" paypalExpress="false"></script><iframe src="https://donorbox.org/embed/supplies-for-dreams" height="685px" width="100%" style="max-width:700px; min-width:310px; max-height:none!important" seamless="seamless" name="donorbox" frameborder="0" scrolling="no" allowpaymentrequest></iframe>
      </div>
    </div>
  </div>
</section>
<section id="donate-content">
  <div class="container py-6">
    <div class="row">
      <div class="col-md-12 col-12">
        <div class="card-deck">
          <div class="card shadow">
            <div class="card-body">
              <i class="far fa-large fa-lightbulb"></i>
              <h5 class="card-title font-weight-bold">Maximize your donation</h5>
              <p class="card-text">We maximize your donation by operating under a student-lead model. </p>
            </div>
            <div class="card-footer">
              <%= link_to 'Learn more about our model <i class="fas fa-arrow-right"></i>'.html_safe, about_path %>
            </div>
          </div>
          <div class="card shadow">
            <div class="card-body">
              <i class="far fa-large fa-file-alt"></i>
              <h5 class="card-title font-weight-bold">View our financials</h5>
              <p class="card-text">We are committed to accountability and transparency.</p>
            </div>
            <div class="card-footer">
              <%= link_to 'View our financials <i class="fas fa-arrow-right"></i>'.html_safe, resources_path %>
            </div>
          </div>
          <div class="card shadow">
            <div class="card-body">
              <i class="fab fa-large fa-acquisitions-incorporated"></i>
              <h5 class="card-title font-weight-bold">Give by check or stock</h5>
              <p class="card-text">We also accept donations by check, stock, and wire transfer.</p>
            </div>
            <div class="card-footer">
              <%= link_to 'Learn more <i class="fas fa-arrow-right"></i>'.html_safe, '/' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/home.html.erb
<% provide(:title, "We Provide Extracurricular Opportunities to CPS Students") %>
<section id="home-banner">
  <div class="stripes">
  </div>
  <div class="home">
    <div class="container">
      <div class="row" style="height: 600px;">
        <div class="offset-md-6 col-md-6 col-12 align-self-center">
          <h1 class="text-white">Zip Codes Shouldn't Limit Learning</h1>
          <p class="p-large py-4">We see a world where the opportunity to learn and achieve is not determined by a person’s neighborhood or class, but by that individual’s passion and persistence for learning.</p>
          <%= link_to "LEARN MORE", programs_path, class: "btn btn-primary btn-red" %>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="home-vision">
  <div class="stripes">
  </div>
  <div class="container">
    <div class="row py-6">
      <div class="col-md-4 col-12 text-center">
        <%= link_to image_tag("home_graphic_3.png", alt: "Home graphic 3", class: "home-graphic") %>
        <h4>Equip Minds</h4>
        <p>We work with Cradles to Crayons to provide students with a year's worth of school supplies.</p>
      </div>
      <div class="col-md-4 col-12 text-center">
        <%= link_to image_tag("home_graphic_2.png", alt: "Home graphic 2", class: "home-graphic") %>
        <h4>Spark Curiosity</h4>
        <p>Our students embark on engaging field trips to Chicago's renowned museums including the Field Museum and Adler Planetarium.</p>
      </div>
      <div class="col-md-4 col-12 text-center">
        <%= link_to image_tag("home_graphic_1.png", alt: "Home graphic 1", class: "home-graphic") %>
        <h4>Unlock Potential</h4>
        <p>College mentors work with students one-on-one to provide life coaching and support academic efforts.</p>
      </div>
    </div>
  </div>
</section>
<section id="home-chicago">
  <div class="stripes">
  </div>
  <div class="chicago py-6">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-12 mobile-pb-6">
          <%= link_to image_tag("chicago_map_blue.png", alt: "Chicago map", style: "width: 90%;") %>
        </div>
        <div class="col-md-6 col-12 align-self-center">
          <h1 class="text-white">We Serve Chicago</h1>
          <p class="p-large py-4">We support schools in various neighborhoods throughout the city including West Ridge, Belmont Cragin, and Humboldt Park. We work with schools that are lead by dedicated staff, active parents, and have high need.</p>
          <%= link_to "Meet our schools", schools_path, class: 'btn btn-primary btn-white' %>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="home-impact">
  <div class="impact pt-6">
    <div class="container">
      <div class="row">
        <div class="offset-md-2 col-md-8 col-12 text-center">
          <h1>Our Impact</h1>
          <p class="p-large py-4">Since 2009, we have served more than 10,000 students across more than a dozen schools and community organizations. We've partnered with dozens of Chicago institutions including Chicago Youth Centers and the Museum of Science and Industry to deliver engaging programs to our students.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="home-aaft">
  <div class="stripes">
  </div>
  <div class="aaft py-6">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-12 mobile-pb-4">
          <div class="card shadow">
            <%= link_to image_tag("sfd_student_1.jpg", alt: "SFD student", class: "card-img-top") %>
            <div class="card-body">
              <p>"I loved going to the Field Museum and seeing Sue the T-Rex. I didn't realize how big dinosaurs were and I learned about why they became extinct"</p>
              <h6 class="text-muted font-weight-bold">FIFTH GRADER, MANUEL PEREZ ELEMENTARY</h6>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-12 align-self-center mobile-pt-6">
          <h1>Experiences Matter</h1>
          <p class="p-large py-4">Our Award-a-Field Trip program takes students to eight museums and cultural sites across Chicago, and provides a rich extra-curricular learning experience that supplements their classroom education.</p>
          <%= link_to "Learn more", programs_path, class: 'btn btn-primary btn-red' %>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="home-stories">
  <div class="container py-6">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="pb-4">Stories From Our Schools</h1>
      </div>
      <div class="col-12">
        <div class="card-deck">
          <% @posts.take(3).each do |post| %>
            <%= render :partial => 'post', :locals => {:post => post} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>